name: Deploy Deno

on:
  push:
    branches:
      - main

env:
  # Update this with the correct project name
  DENO_PROJECT_NAME: francescogu-examples-he-63

jobs:
  deploy:
    permissions:
      id-token: write # required
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        id: deploy
        with:
          project: ${{ env.DENO_PROJECT_NAME }}
          entrypoint: main.ts

      - name: Register Restate deployment
        env:
          # In your Restate Cloud dashboard, go to Developers > API Keys > Create API Key, and make sure to select **Admin** for role
          RESTATE_ADMIN_URL: ${{ secrets.RESTATE_ADMIN_URL }}
          # You can find this out in Developers > Invoke. For example: `https://some-environment-private-id.env.us.restate.cloud:9070`
          RESTATE_AUTH_TOKEN: ${{ secrets.RESTATE_AUTH_TOKEN }}        
        run: |
          # Revision URL https://docs.deno.com/deploy/classic/deployments/#production-vs.-preview-deployments
          npx -y @restatedev/restate deployment register -y https://${{ env.DENO_PROJECT_NAME }}-${{ steps.deploy.outputs.deployment-id }}.deno.dev