name: Deploy Deno

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write # required
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deploy Deno
        run: deno deploy --org slinkydeveloper